# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b509adf8560d7031e90166df84a78dc334dfe09bffb0974274d17736f27b7efa31349d16354bcf4e6989a913b960bb29f4cc022c850a172b40dda26279a4b1d

test:
  secret_key_base: b9062fe6a53d9a0e238f7a04cd6cc5f89b9bb476873de42d10676a4c95613dba7a01d5fc2cf3d212f980705c0e454e5c5599159e2cbe54310ebcbbe31d7c64cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
